[package]
name = "plage"
version = "1.0.0"
authors = ["cavery <averylapine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lliw = "0.1"
users = "0.11"
